RulesOfTheGame/RulesOfTheGame/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RulesOfTheGame.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        public ActionResult Flappy_Bird()
        {
            return View();
        }
        public ActionResult Guide_The_Goat()
        {
            return View();
        }

        public ActionResult TeeTrees()
        {
            return View();
        }

        public ActionResult Bubble_Pop()
        {
            return View();
        }
    }
}

RulesOfTheGame/RulesOfTheGame/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO.Compression;
using System.IO;
using Microsoft.VisualBasic;

namespace RulesOfTheGame.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Information about the site.";

            return View();
        }

        public ActionResult Games()
        {
            ViewBag.Message = "Where the fun begins!";

            return View();
        }

        [HttpPost]
        public ActionResult Games(HttpPostedFileBase zip)
        {
            ViewBag.Message = "Where the fun begins!";

            var uploads = Server.MapPath("~/Content/TempAddGame");
            using (ZipArchive archive = new ZipArchive(zip.InputStream))
            {
                foreach (ZipArchiveEntry entry in archive.Entries)
                {
                    if (!string.IsNullOrEmpty(Path.GetExtension(entry.FullName))) //make sure it's not a folder
                    {
                        entry.ExtractToFile(Path.Combine(uploads, entry.FullName));
                    }
                    else
                    {
                        Directory.CreateDirectory(Path.Combine(uploads, entry.FullName));
                    }
                }
            }
            ViewBag.Files = Directory.EnumerateFiles(uploads);

            try
            {
                NewGame myNewGame = new NewGame();
                ProcessDirectory(uploads, ref myNewGame);

                var newGameLoc = Server.MapPath("~/Content/");
                if (myNewGame.gamemanifest && myNewGame.gamescript && myNewGame.ContentFolder && myNewGame.ImagesFolder && myNewGame.ScreenshotFolder && myNewGame.screenshot)
                {
                    using (StreamWriter sw = System.IO.File.AppendText(Server.MapPath("~/Views/Home/gamesmanifest.txt")))
                    {
                        string[] manifestInfo = System.IO.File.ReadAllLines(myNewGame.ManifestLocation);
                        //sw.WriteLine();
                        sw.WriteLine("\n" + manifestInfo[0]);
                    }
                    new Microsoft.VisualBasic.Devices.Computer().FileSystem.CopyDirectory(myNewGame.ContentFolderLocation, newGameLoc);
                }
            }
            catch (Exception e){ }

            System.IO.DirectoryInfo di = new DirectoryInfo(uploads);

            foreach (FileInfo file in di.GetFiles())
            {
                file.Delete();
            }
            foreach (DirectoryInfo dir in di.GetDirectories())
            {
                dir.Delete(true);
            }
            //Array.ForEach(Directory.GetFiles((string)uploads), System.IO.File.Delete);
            //string[] filePaths = Directory.GetFiles(uploads);
            //foreach (string filePath in filePaths)
            //    System.IO.File.Delete(filePath);

            return View();
        }

        public class NewGame
        {
            public string ContentFolderLocation { get; set; }

            public string ManifestLocation { get; set; }
            public bool gamemanifest { get; set; }

            public bool gamescript { get; set; }

            public bool screenshot { get; set; }

            public bool ContentFolder { get; set; }

            public bool ImagesFolder { get; set; }

            public bool ScreenshotFolder { get; set; }
        }

        public void ProcessDirectory(string targetDirectory, ref NewGame myNewGame)
        {
            // Process the list of files found in the directory.
            string[] fileEntries = Directory.GetFiles(targetDirectory);
            foreach (string fileName in fileEntries)
            {
                //ProcessFile(fileName, ref myNewGame);

                if (fileName.Contains("screenshot"))
                {
                    myNewGame.screenshot = true;
                }
                if (fileName.Contains("gamesmanifest"))
                {
                    myNewGame.ManifestLocation = fileName;
                    myNewGame.gamemanifest = true;
                }
                if (fileName.Contains("gamescript"))
                {
                    myNewGame.gamescript = true;
                }
            }

            // Recurse into subdirectories of this directory.
            string[] subdirectoryEntries = Directory.GetDirectories(targetDirectory);
            foreach (string subdirectory in subdirectoryEntries)
            {
                if (subdirectory.Contains("Content\\images\\screenshots"))
                {
                    myNewGame.ContentFolder = true;
                    myNewGame.ImagesFolder = true;
                    myNewGame.ScreenshotFolder = true;
                    myNewGame.ContentFolderLocation = subdirectory.Replace("\\images\\screenshots", string.Empty);
                }
                ProcessDirectory(subdirectory, ref myNewGame);
            }
        }

        public void ProcessFile(string path, ref NewGame myNewGame)
        {
            Console.WriteLine("Processed file '{0}'.", path);
        }

        public ActionResult HighScore()
        {
            return View();
        }
    
        public ActionResult DynamicGamePage(string id)
        {
            ViewData["Webpage"] = id;
            return View();
        }

    }
}

RulesOfTheGame/RulesOfTheGame/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

<ul>
    <li>To play a game, click on the Game tab on the navigation bar. </li>
    <li>Register for an account so you can be on the leaderboards.</li>
    <li>Upload your own game! However, make sure your game fits the following requirements.</li>
    <ul>
        <li>Have a gamesmanifest file with the name of your game in it (case sensitive).</li>
        <li>Have a picture for a game image containing the word, "screenshot" in it.</li>
        <li>Have a gamescripts file with the name of your game (case sensitive), as well as any scripts you use for your game.</li>
    </ul>
    <li>Lastly, have fun!</li>
</ul>

RulesOfTheGame/RulesOfTheGame/Views/Home/DynamicGamePage.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*<script>
    $('html, body').css({
        overflow: 'hidden',
        height: '100%'
    });
</script>*@

@{
    var webpage = ViewData["Webpage"];

    var result = "";
    Array userData = null;
    char[] delimiterChar = { ',' };

    var dataFile = Server.MapPath("~/Content/" + webpage + "/gamescripts.txt");

    if (File.Exists(dataFile))
    {
        userData = File.ReadAllLines(dataFile);
        if (userData == null)
        {
            // Empty file.
            result = "The file is empty.";
        }
    }
    else
    {
        // File does not exist.
        result = "The file does not exist.";
    }
}

@{
    int i = 0;
    foreach (string s in userData)
    {
        if (i == 0)
        {
            <h2>@s</h2>;
        }

        if (i > 0)
        {
            <script language="javascript" type="text/javascript" src="@s"></script>;
        }
        i++;
    }
}

<script>
    var root = "@Url.Content("~")";
</script>

<div id="sketch-holder">
</div>

RulesOfTheGame/RulesOfTheGame/Views/Home/Games.cshtml
@{
    ViewBag.Title = "Games";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

@{
    var result = "";
    Array userData = null;
    char[] delimiterChar = { ',' };

    var dataFile = Server.MapPath("~/Views/Home/gamesmanifest.txt");

    if (File.Exists(dataFile))
    {
        userData = File.ReadAllLines(dataFile);
        if (userData == null)
        {
            // Empty file.
            result = "The file is empty.";
        }
    }
    else
    {
        // File does not exist.
        result = "The file does not exist.";
    }
}

@if (User.IsInRole("Admin"))
{
    using (Html.BeginForm("Games", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div style="border:1px groove grey; padding:5px; width:33%; text-align:center; vertical-align:middle;">
            <h2>Upload New Game</h2>
            <div>
                <input type="file" name="zip"/><br />
            </div>
            <div>
                <button class="btn btn-default">Submit</button>
            </div>
        </div>
    }
}

<div class="row">
    @foreach (string s in userData)
    {
        //@:console.log("@s");
        string[] names = s.Split(',');
        string temp = names[0];
        temp = temp.Replace(' ', '_');
        if (names.Length < 2 || temp.IsEmpty())
        {

        }
        else
        {
            <div class="col-md-3">
                <h4>@Html.ActionLink(names[0], "DynamicGamePage", "Home", new { id = temp }, null)</h4>
                <img src="~/Content/images/screenshots/@names[1]" height="256" width="192" />
            </div>
        }
    }
</div>

@*<div class="row">
    <div class="col-md-3">
        <h4>@Html.ActionLink("Flappy Bird", "Flappy_Bird", "Game")</h4>
        <img src="~/Content/images/screenshots/Flappy-Bird-Screenshot.png" height="256" width="192"/>
    </div>
    <div class="col-md-3">
        <h4>@Html.ActionLink("Guide The Goat", "Guide_The_Goat", "Game")</h4>
        <img src="~/Content/images/screenshots/goatScreenshot.png" height="256" width="192" />
    </div>
    <div class="col-md-3">
        <div class="col-md-3">
            <h4>@Html.ActionLink("TeeTrees", "TeeTrees", "Game")</h4>
            <img src="~/Content/Teetrees/TeetreesThumbnail.png" height="256" width="192" />
        </div>
    </div>
    <div class="col-md-3">
        <div class="col-md-3">
            <h4>@Html.ActionLink("Bubble Pop", "Bubble_Pop", "Game")</h4>
            <img src="~/Content/images/screenshots/bubbleScreenshot.PNG" height="256" width="192" />
        </div>
    </div>
</div>*@

RulesOfTheGame/RulesOfTheGame/Views/Home/HighScore.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    table {  
    color: #333;
    font-family: Helvetica, Arial, sans-serif;
    width: 640px; 
    border-collapse: 
    collapse; border-spacing: 0; 
}

td, th {  
    border: 1px solid transparent; /* No more visible border */
    height: 30px; 
    transition: all 0.3s;  /* Simple transition for hover effect */
}

th {  
    background: #DFDFDF;  /* Darken header a bit */
    font-weight: bold;
}

td {  
    background: #FAFAFA;
    text-align: center;
}

/* Cells in even rows (2,4,6...) are one color */        
tr:nth-child(even) td { background: #F1F1F1; }   

/* Cells in odd rows (1,3,5...) are another (excludes header cells)  */        
tr:nth-child(odd) td { background: #FEFEFE; }  

tr td:hover { background: #666; color: #FFF; }  
/* Hover cell effect! */
</style>

<script>
    var bestScores;
    $(document).ready(function () {
        getBestScores();
        console.log(bestScores);
        for (var i = 0; i < bestScores.length; i++) {
            $('#highScore').append('<tr><td>' + bestScores[i].Game + '</td><td>' + bestScores[i].User + '</td><td>' + bestScores[i].Val + '</td></tr>');
        }
    });
</script>

<table id="highScore">
    <tr>
        <th>Game</th>
        <th>User</th>
        <th>Score</th>
    </tr>
    @*<tr>
        <th>Flappy Bird</th>
        <th>Guide The Goat</th>
        <th>Bubble Pop</th>
        <th>TeeTrees</th>
    </tr>
    <tr>
        <td>5</td>
        <td>100</td>
        <td>400</td>
        <td>1000</td>
    </tr>*@
</table>

RulesOfTheGame/RulesOfTheGame/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Rules Of The Game</h1>
    <p class="lead">This website is to provide fun games for when you have downtime between classes and homework.</p>
    @*<p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Create an account to get started on Rules of The Game. It will allow you to have access to great features like leaderboards and commenting.
        </p>
        @*<p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>*@
    </div>
    @*<div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>*@
</div>